version: '3.7'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql:cached

  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solidus_starter_frontend_solidus_test
    volumes:
      - postgres:/var/lib/postgresql/data:cached

  app:
    build:
      context: .dockerdev
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: "2.7.2"
        PG_VERSION: 13
        NODE_VERSION: 14
        MYSQL_VERSION: "8.0"
        BUNDLER_VERSION: 2
    image: solidus_starter_frontend-0.1.0
    command: bash -c "tail -f /dev/null"
    environment:
      CAPYBARA_JS_DRIVER: apparition_docker_friendly
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_ALL: "1"
      DB_MYSQL_HOST: mysql
      DB_POSTGRES_HOST: postgres
      HISTFILE: "/home/solidus_starter_frontend_user/history/bash_history"
      MYSQL_HISTFILE: "/home/solidus_starter_frontend_user/history/mysql_history"
    ports:
      - "${SANDBOX_PORT:-3000}:${SANDBOX_PORT:-3000}"
    volumes:
      - .:/home/solidus_starter_frontend_user/app:delegated
      - bundle:/home/solidus_starter_frontend_user/gems:cached
      - history:/home/solidus_starter_frontend_user/history:cached
      - .dockerdev/.psqlrc:/home/solidus_starter_frontend_user/.psqlrc:cached
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp
    depends_on:
      - mysql
      - postgres

volumes:
  bundle:
  history:
  postgres:
  mysql:
