version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0
  slack: circleci/slack@4.9.3

  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

commands:
  setup:
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: Install libvips
          command: |
            sudo apt-get update
            sudo apt-get install -yq libvips-dev

  test-branch:
    description:
      Runs tests for a specific Solidus branch.

    parameters:
      branch:
        type: string
        default: master
      command:
        type: string
        default: |
          cd sandbox
          bundle add rspec_junit_formatter --group test
          bundle exec rspec --format progress --format RspecJunitFormatter --out $TEST_RESULTS_PATH
      command_verb:
        type: string
        default: Runs tests
      rails_version:
        type: string

    steps:
      - run:
          name: 'Solidus <<parameters.branch>>:  Install gems'
          command: |
            bundle install
          environment:
            RAILS_VERSION: <<parameters.rails_version>>
            SOLIDUS_BRANCH: <<parameters.branch>>
          when: always
      - run:
          name: 'Solidus <<parameters.branch>>:  Install sandbox with generated starter frontend'
          command: bin/sandbox --seed=false --sample=false
          environment:
            RAILS_ENV: development # if run in test mode will attempt to eager-load and break the sandbox
            RAILS_VERSION: <<parameters.rails_version>>
            SANDBOX_BUNDLE_PATH: ../vendor/bundle/<<parameters.branch>>
            SOLIDUS_BRANCH: <<parameters.branch>>
          when: always
      - run:
          name: '<<parameters.command_verb>> on Solidus <<parameters.branch>>'
          command: <<parameters.command>>
          environment:
            RAILS_VERSION: <<parameters.rails_version>>
            SOLIDUS_BRANCH: <<parameters.branch>>
            TEST_RESULTS_PATH: ../test-results/gems-v3-ruby-v2-7-solidus-<<parameters.branch>>/results.xml
          when: always
      - run:
          command: rm -rf sandbox
          name: 'Solidus <<parameters.branch>>: Clean up'
          when: always

  notify:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
          branch_pattern: main, v[0-9]+\.[0-9]+

jobs:
  run-specs:
    executor:
        name: solidusio_extensions/<<parameters.database>>
        ruby_version: <<parameters.ruby_version>>
    steps:
      - setup
      - test-branch:
          branch: <<parameters.solidus_branch>>
          rails_version: <<parameters.rails_version>>
      - solidusio_extensions/store-test-results
      - notify
    parameters:
      solidus_branch:
        type: string
        default: 'master'
      rails_version:
        type: string
        default: '~> 7.0'
      ruby_version:
        type: string
        default: '3.2'
      database:
        type: string
        default: 'postgres'

workflows:
  "Run specs on development Solidus version":
    jobs:
      - run-specs:
          context: slack-secrets
          name: run-specs-with-postgres

      - run-specs:
          context: slack-secrets
          name: run-specs-with-mysql
          database: 'mysql'

      - run-specs:
          context: slack-secrets
          name: run-specs-with-postgres-ruby-3-1
          ruby_version: '3.1'

      - run-specs:
          context: slack-secrets
          name: run-specs-with-postgres-ruby-2-7
          ruby_version: '2.7'

  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs:
          context: slack-secrets
          name: run-specs-with-solidus-3-2-rails-7-ruby-3-1-postgres

      - run-specs:
          context: slack-secrets
          name: run-specs-but-with-solidus-latest
          solidus_branch: 'master'

      - run-specs:
          context: slack-secrets
          name: run-specs-but-with-rails-6
          rails_version: '~> 6.1'

      - run-specs:
          context: slack-secrets
          name: run-specs-but-with-ruby-3-0
          ruby_version: '3.0'

      - run-specs:
          context: slack-secrets
          name: run-specs-but-with-ruby-2
          ruby_version: '2.7'

      - run-specs:
          context: slack-secrets
          name: run-specs-but-with-mysql
          database: 'mysql'
